server:
  port: 6136

spring:
  datasource:
    username: root
    password: sql3.14
    url: jdbc:mysql://localhost:3306/cet6?useUnicode=true&characterEncoding=UTF-8&&serverTimezone=GMT%2B8
logging:
  level:
    com.nku: debug
redis:
  port:6379
  host:localhost